Homework 1 / Refactor
GenesisEducationKyiv/main-project-lumenalux pull request #3
Opened 2023-06-19 16:50 UTC by lumenalux

This pull request includes significant improvements to the codebase, including code refactoring, increased test coverage, and an enhanced file structure. The changes made in this pull request aim to improve the maintainability, readability, and overall quality of the project. Here's an overview of the key modifications:

## Code Refactoring:

- Refactored existing codebase to adhere to best practices and established coding conventions.
- Improved variable names, function names, and overall code readability.
- Eliminated code duplication and applied appropriate design patterns where applicable.

## File Structure:

- Restructured the project directory to enhance organization and maintainability.
- Introduced a logical and intuitive folder structure for different modules and components.
- Updated file and folder naming conventions for consistency and clarity.

2023-06-20 08:25 UTC, delveper requested changes

2023-06-20 08:25 UTC, delveper commented on internal/email/smtp.go
> +
Looks like YAGNI. Are you sure about all those methods?

2023-06-20 08:25 UTC, delveper commented on internal/email/smtp.go
> +) (SMTPConnectionClient, error) {
A rule of thumb is to accept interfaces and returning structs.

2023-06-20 08:25 UTC, delveper commented on internal/rate/kuna_provider.go
> +	var data [][]interface{}
Looks like a lot of magic down here.  You can declare struct that will hold on all needful data and be explicit.

2023-06-20 08:25 UTC, delveper commented on internal/subscription/service.go
> +	Read() ([][]string, error)
It is not absolutely obvious what Read method does. Renaming method or using named output parameters can fix this.

2023-06-20 08:25 UTC, delveper commented on internal/subscription/service.go
> +
This blank line after function signature  is driving me crazy 😄

2023-06-20 08:25 UTC, delveper commented on pkg/config/config.go
> +	yaml "gopkg.in/yaml.v2"
Redundant alias.

2023-06-20 08:25 UTC, delveper commented on pkg/config/config.go
> +	return err
It is confusing that is no happy path,  it is much better to `return yaml.Unmarshal(data, &configuration)`, Having "return nil" is in the last line is good practice, though

2023-06-20 08:25 UTC, delveper commented on pkg/config/model.go
> +package config
Centralizing configuration can be beneficial, but it is important to consider the trade-offs. Having a config package that is directly imported by every package can lead to tight coupling, which can make code more difficult to maintain and less flexible. A better approach is to inject  configuration specific to each package. This will allow each package to be independent, making it easier to maintain and more flexible.
Of course,  if your application is small and simple, then a centralized configuration package may be sufficient.

2023-06-20 08:25 UTC, delveper commented on internal/email/service.go
> +		log.Fatal(err)
The idea that fatality can happen and app will crash is terrifying. It is reasonable to throw and error that can be handled by the caller rather give him specific to http status code.

2023-06-20 08:25 UTC, delveper commented on internal/controllers/controller.go
> +	err = json.NewEncoder(w).Encode(exchangeRate)
Shadowing errors is not bad at all. I noticed that you recently use `err =` declaration. Frankly speaking I sleep better when use `err :=`

2023-06-21 10:25 UTC, lumenalux commented on internal/email/smtp.go
> +
Yes, all methods are used in this layer. It would be possible to separate the interfaces so that each has one or two methods. On the other hand it just so happens that smtp client is used in so many places in this layer and without any one of these methods it would break the logic of the application

2023-06-21 10:45 UTC, lumenalux commented on internal/controllers/controller.go
> +	err = json.NewEncoder(w).Encode(exchangeRate)
I didn't understand you at this point. If I change `err =` to `err :=` then my project just won't compile)

2023-06-21 13:57 UTC, delveper reviewed
I would recommend wrapping errors with additional context. This can make it easier to to track down the source of an error.

2023-06-21 15:15 UTC, lumenalux commented on Dockerfile
>  RUN touch storage.csv
Yes, you are absolutely right. It seems to be important. I will add docker compose

2023-06-21 15:16 UTC, lumenalux commented on pkg/config/config.go
> +var configuration Config
Absolutely not. Deprecated part of code

2023-06-21 16:12 UTC, delveper approved these changes
Well done!

2023-06-26 07:01 UTC, andrey-filenko-quarks-tech commented on internal/email/service.go
> +	clientConnection, err := client.Connect()
I guess creation new connection on every request is kind of heavy operation, consider doing it once on program bootstraping

2023-06-26 07:03 UTC, andrey-filenko-quarks-tech commented on internal/subscription/service.go
> +type ServiceImpl struct {
Impl suffix is not very idiomatic for go, consider placing interfaces near the place of their usage, so here you can name implemetation as Service

2023-06-26 09:12 UTC, lumenalux commented on internal/subscription/service.go
> +type ServiceImpl struct {
Good point. Moved interfaces to the places of use. Fixes in commits 5d18ab7, b10a326

2023-06-26 13:46 UTC, delveper approved these changes

2023-06-26 13:46 UTC, delveper commented on internal/rate/provider.go
> +package rate
There is no need to create a new file just for a single interface. You could move it directly to service.go. Creating contracts.go or a similar file to store all interfaces that are used at the package level is also a reasonable approach

2023-06-26 14:55 UTC, lumenalux commented on internal/email/service.go
> +) (int, error) {
Got the idea. Fixed in e019160

2023-06-26 22:49 UTC, delveper approved these changes

2023-06-28 08:09 UTC, merged